services:
  app:
    image: python:3.11
    ports:
      - 8050:8050
    volumes:
      - .:/home
    working_dir: /home
    command: sh -c "pip install --user -r requirements.txt; python dashboard.py"
    